# Generated by Django 5.0.6 on 2024-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenueStation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
