# Generated by Django 5.0.6 on 2024-08-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventStation', '0005_eventdetails_reg_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
